import Head from 'next/head';
import Layout from '@/components/Layout';

interface IProps {
  role: string;
}

function Home({ role }: IProps) {
  return (
    <>
      <Head>
        <title>Home - Clients App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>This is Clients App</h1>
      </Layout>
    </>
  );
}
Home.getInitialProps = async ({ req }: any) => {
  const isServer = !!req;
  let role;

  if (isServer) {
    console.log(req?.headers?.cookie);
    // role = getCookie('token', req?.headers?.cookie);
  } else {
    console.log('testst');
    // role = cookieCutter.get('token');
  }
  return { role };
};

export default Home;
